version: "3.9"

services:
  api:
    build:
      context: . 
      dockerfile: Dockerfile
    command: /Start 
    container_name: api
    volumes: 
      - .:/app 
      - static-volume:/app/staticfiles 
      - media-volume:/app/mediafiles
    expose: 
      - "8000"
    env_file:
      - ./.env
    depends_on: 
      - postgres 
    networks: 
      - instagram-clone
  
  postgres: 
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: instagramclone
    networks:
      - instagram-clone
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  nginx: 
    restart: always 
    depends_on:
      - api 
    volumes:
      - static-volume:/app/staticfiles
      - media-volume:/app/mediafiles
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - instagram-clone
    


networks: 
  instagram-clone:
    driver: bridge 

volumes:
  static-volume: 
  media-volume: 
  dev-db-data:
