# Generated by Django 4.1.2 on 2022-10-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y', max_length=255),
        ),
    ]
